/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as SeasonRouteImport } from './routes/season'
import { Route as SendYourAgentRouteImport } from './routes/send-your-agent'
import { Route as SkillDotmdRouteImport } from './routes/skill[.]md'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminArenaRouteImport } from './routes/admin.arena'
import { Route as AdminConversationsRouteImport } from './routes/admin.conversations'
import { Route as AdminDemoAgentsRouteImport } from './routes/admin.demo-agents'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminVisualPostsRouteImport } from './routes/admin.visual-posts'
import { Route as AgentSlugRouteImport } from './routes/agent.$slug'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as AdminAgentsAgentIdRouteImport } from './routes/admin.agents.$agentId'
import { Route as ApiCronRunDemoAgentRouteImport } from './routes/api/cron/run-demo-agent'
import { Route as ApiPublicAgentRegisterRouteImport } from './routes/api/public/agent-register'
import { Route as ApiPublicAgentApiSplatRouteImport } from './routes/api/public/agent-api.$'
import { Route as ApiPublicAgentAvatarSplatRouteImport } from './routes/api/public/agent-avatar.$'
import { Route as ApiPublicArenaSplatRouteImport } from './routes/api/public/arena.$'
import { Route as ApiPublicConversationsSplatRouteImport } from './routes/api/public/conversations.$'
import { Route as ApiPublicHooksRewardsTickRouteImport } from './routes/api/public/hooks/rewards-tick'
import { Route as ApiPublicHooksRunDemoAgentRouteImport } from './routes/api/public/hooks/run-demo-agent'
import { Route as ApiPublicHooksRunDemoCampaignRouteImport } from './routes/api/public/hooks/run-demo-campaign'
import { Route as ApiPublicPostVisualSplatRouteImport } from './routes/api/public/post-visual.$'
import { Route as ApiPublicRewardsSplatRouteImport } from './routes/api/public/rewards.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonRoute = SeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => rootRouteImport,
} as any)
const SendYourAgentRoute = SendYourAgentRouteImport.update({
  id: '/send-your-agent',
  path: '/send-your-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillDotmdRoute = SkillDotmdRouteImport.update({
  id: '/skill.md',
  path: '/skill.md',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArenaRoute = AdminArenaRouteImport.update({
  id: '/admin/arena',
  path: '/admin/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/admin/conversations',
  path: '/admin/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemoAgentsRoute = AdminDemoAgentsRouteImport.update({
  id: '/admin/demo-agents',
  path: '/admin/demo-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/admin/rewards',
  path: '/admin/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisualPostsRoute = AdminVisualPostsRouteImport.update({
  id: '/admin/visual-posts',
  path: '/admin/visual-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSlugRoute = AgentSlugRouteImport.update({
  id: '/agent/$slug',
  path: '/agent/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsAgentIdRoute = AdminAgentsAgentIdRouteImport.update({
  id: '/admin/agents/$agentId',
  path: '/admin/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRunDemoAgentRoute = ApiCronRunDemoAgentRouteImport.update({
  id: '/api/cron/run-demo-agent',
  path: '/api/cron/run-demo-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRegisterRoute = ApiPublicAgentRegisterRouteImport.update({
  id: '/api/public/agent-register',
  path: '/api/public/agent-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentApiSplatRoute = ApiPublicAgentApiSplatRouteImport.update({
  id: '/api/public/agent-api/$',
  path: '/api/public/agent-api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentAvatarSplatRoute =
  ApiPublicAgentAvatarSplatRouteImport.update({
    id: '/api/public/agent-avatar/$',
    path: '/api/public/agent-avatar/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicArenaSplatRoute = ApiPublicArenaSplatRouteImport.update({
  id: '/api/public/arena/$',
  path: '/api/public/arena/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConversationsSplatRoute =
  ApiPublicConversationsSplatRouteImport.update({
    id: '/api/public/conversations/$',
    path: '/api/public/conversations/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRewardsTickRoute =
  ApiPublicHooksRewardsTickRouteImport.update({
    id: '/api/public/hooks/rewards-tick',
    path: '/api/public/hooks/rewards-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunDemoAgentRoute =
  ApiPublicHooksRunDemoAgentRouteImport.update({
    id: '/api/public/hooks/run-demo-agent',
    path: '/api/public/hooks/run-demo-agent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunDemoCampaignRoute =
  ApiPublicHooksRunDemoCampaignRouteImport.update({
    id: '/api/public/hooks/run-demo-campaign',
    path: '/api/public/hooks/run-demo-campaign',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPostVisualSplatRoute =
  ApiPublicPostVisualSplatRouteImport.update({
    id: '/api/public/post-visual/$',
    path: '/api/public/post-visual/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRewardsSplatRoute = ApiPublicRewardsSplatRouteImport.update({
  id: '/api/public/rewards/$',
  path: '/api/public/rewards/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/rewards': typeof RewardsRoute
  '/season': typeof SeasonRoute
  '/send-your-agent': typeof SendYourAgentRoute
  '/skill.md': typeof SkillDotmdRoute
  '/admin/arena': typeof AdminArenaRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/demo-agents': typeof AdminDemoAgentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/visual-posts': typeof AdminVisualPostsRoute
  '/agent/$slug': typeof AgentSlugRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/api/cron/run-demo-agent': typeof ApiCronRunDemoAgentRoute
  '/api/public/agent-register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent-api/$': typeof ApiPublicAgentApiSplatRoute
  '/api/public/agent-avatar/$': typeof ApiPublicAgentAvatarSplatRoute
  '/api/public/arena/$': typeof ApiPublicArenaSplatRoute
  '/api/public/conversations/$': typeof ApiPublicConversationsSplatRoute
  '/api/public/hooks/rewards-tick': typeof ApiPublicHooksRewardsTickRoute
  '/api/public/hooks/run-demo-agent': typeof ApiPublicHooksRunDemoAgentRoute
  '/api/public/hooks/run-demo-campaign': typeof ApiPublicHooksRunDemoCampaignRoute
  '/api/public/post-visual/$': typeof ApiPublicPostVisualSplatRoute
  '/api/public/rewards/$': typeof ApiPublicRewardsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/rewards': typeof RewardsRoute
  '/season': typeof SeasonRoute
  '/send-your-agent': typeof SendYourAgentRoute
  '/skill.md': typeof SkillDotmdRoute
  '/admin/arena': typeof AdminArenaRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/demo-agents': typeof AdminDemoAgentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/visual-posts': typeof AdminVisualPostsRoute
  '/agent/$slug': typeof AgentSlugRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/api/cron/run-demo-agent': typeof ApiCronRunDemoAgentRoute
  '/api/public/agent-register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent-api/$': typeof ApiPublicAgentApiSplatRoute
  '/api/public/agent-avatar/$': typeof ApiPublicAgentAvatarSplatRoute
  '/api/public/arena/$': typeof ApiPublicArenaSplatRoute
  '/api/public/conversations/$': typeof ApiPublicConversationsSplatRoute
  '/api/public/hooks/rewards-tick': typeof ApiPublicHooksRewardsTickRoute
  '/api/public/hooks/run-demo-agent': typeof ApiPublicHooksRunDemoAgentRoute
  '/api/public/hooks/run-demo-campaign': typeof ApiPublicHooksRunDemoCampaignRoute
  '/api/public/post-visual/$': typeof ApiPublicPostVisualSplatRoute
  '/api/public/rewards/$': typeof ApiPublicRewardsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/rewards': typeof RewardsRoute
  '/season': typeof SeasonRoute
  '/send-your-agent': typeof SendYourAgentRoute
  '/skill.md': typeof SkillDotmdRoute
  '/admin/arena': typeof AdminArenaRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/demo-agents': typeof AdminDemoAgentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/visual-posts': typeof AdminVisualPostsRoute
  '/agent/$slug': typeof AgentSlugRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/api/cron/run-demo-agent': typeof ApiCronRunDemoAgentRoute
  '/api/public/agent-register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent-api/$': typeof ApiPublicAgentApiSplatRoute
  '/api/public/agent-avatar/$': typeof ApiPublicAgentAvatarSplatRoute
  '/api/public/arena/$': typeof ApiPublicArenaSplatRoute
  '/api/public/conversations/$': typeof ApiPublicConversationsSplatRoute
  '/api/public/hooks/rewards-tick': typeof ApiPublicHooksRewardsTickRoute
  '/api/public/hooks/run-demo-agent': typeof ApiPublicHooksRunDemoAgentRoute
  '/api/public/hooks/run-demo-campaign': typeof ApiPublicHooksRunDemoCampaignRoute
  '/api/public/post-visual/$': typeof ApiPublicPostVisualSplatRoute
  '/api/public/rewards/$': typeof ApiPublicRewardsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/how-it-works'
    | '/leaderboards'
    | '/rewards'
    | '/season'
    | '/send-your-agent'
    | '/skill.md'
    | '/admin/arena'
    | '/admin/conversations'
    | '/admin/demo-agents'
    | '/admin/login'
    | '/admin/rewards'
    | '/admin/visual-posts'
    | '/agent/$slug'
    | '/agents/$agentId'
    | '/posts/$postId'
    | '/admin/'
    | '/admin/agents/$agentId'
    | '/api/cron/run-demo-agent'
    | '/api/public/agent-register'
    | '/api/public/agent-api/$'
    | '/api/public/agent-avatar/$'
    | '/api/public/arena/$'
    | '/api/public/conversations/$'
    | '/api/public/hooks/rewards-tick'
    | '/api/public/hooks/run-demo-agent'
    | '/api/public/hooks/run-demo-campaign'
    | '/api/public/post-visual/$'
    | '/api/public/rewards/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/how-it-works'
    | '/leaderboards'
    | '/rewards'
    | '/season'
    | '/send-your-agent'
    | '/skill.md'
    | '/admin/arena'
    | '/admin/conversations'
    | '/admin/demo-agents'
    | '/admin/login'
    | '/admin/rewards'
    | '/admin/visual-posts'
    | '/agent/$slug'
    | '/agents/$agentId'
    | '/posts/$postId'
    | '/admin'
    | '/admin/agents/$agentId'
    | '/api/cron/run-demo-agent'
    | '/api/public/agent-register'
    | '/api/public/agent-api/$'
    | '/api/public/agent-avatar/$'
    | '/api/public/arena/$'
    | '/api/public/conversations/$'
    | '/api/public/hooks/rewards-tick'
    | '/api/public/hooks/run-demo-agent'
    | '/api/public/hooks/run-demo-campaign'
    | '/api/public/post-visual/$'
    | '/api/public/rewards/$'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/how-it-works'
    | '/leaderboards'
    | '/rewards'
    | '/season'
    | '/send-your-agent'
    | '/skill.md'
    | '/admin/arena'
    | '/admin/conversations'
    | '/admin/demo-agents'
    | '/admin/login'
    | '/admin/rewards'
    | '/admin/visual-posts'
    | '/agent/$slug'
    | '/agents/$agentId'
    | '/posts/$postId'
    | '/admin/'
    | '/admin/agents/$agentId'
    | '/api/cron/run-demo-agent'
    | '/api/public/agent-register'
    | '/api/public/agent-api/$'
    | '/api/public/agent-avatar/$'
    | '/api/public/arena/$'
    | '/api/public/conversations/$'
    | '/api/public/hooks/rewards-tick'
    | '/api/public/hooks/run-demo-agent'
    | '/api/public/hooks/run-demo-campaign'
    | '/api/public/post-visual/$'
    | '/api/public/rewards/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  RewardsRoute: typeof RewardsRoute
  SeasonRoute: typeof SeasonRoute
  SendYourAgentRoute: typeof SendYourAgentRoute
  SkillDotmdRoute: typeof SkillDotmdRoute
  AdminArenaRoute: typeof AdminArenaRoute
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminDemoAgentsRoute: typeof AdminDemoAgentsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminVisualPostsRoute: typeof AdminVisualPostsRoute
  AgentSlugRoute: typeof AgentSlugRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAgentsAgentIdRoute: typeof AdminAgentsAgentIdRoute
  ApiCronRunDemoAgentRoute: typeof ApiCronRunDemoAgentRoute
  ApiPublicAgentRegisterRoute: typeof ApiPublicAgentRegisterRoute
  ApiPublicAgentApiSplatRoute: typeof ApiPublicAgentApiSplatRoute
  ApiPublicAgentAvatarSplatRoute: typeof ApiPublicAgentAvatarSplatRoute
  ApiPublicArenaSplatRoute: typeof ApiPublicArenaSplatRoute
  ApiPublicConversationsSplatRoute: typeof ApiPublicConversationsSplatRoute
  ApiPublicHooksRewardsTickRoute: typeof ApiPublicHooksRewardsTickRoute
  ApiPublicHooksRunDemoAgentRoute: typeof ApiPublicHooksRunDemoAgentRoute
  ApiPublicHooksRunDemoCampaignRoute: typeof ApiPublicHooksRunDemoCampaignRoute
  ApiPublicPostVisualSplatRoute: typeof ApiPublicPostVisualSplatRoute
  ApiPublicRewardsSplatRoute: typeof ApiPublicRewardsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season': {
      id: '/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof SeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-your-agent': {
      id: '/send-your-agent'
      path: '/send-your-agent'
      fullPath: '/send-your-agent'
      preLoaderRoute: typeof SendYourAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill.md': {
      id: '/skill.md'
      path: '/skill.md'
      fullPath: '/skill.md'
      preLoaderRoute: typeof SkillDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/arena': {
      id: '/admin/arena'
      path: '/admin/arena'
      fullPath: '/admin/arena'
      preLoaderRoute: typeof AdminArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/admin/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demo-agents': {
      id: '/admin/demo-agents'
      path: '/admin/demo-agents'
      fullPath: '/admin/demo-agents'
      preLoaderRoute: typeof AdminDemoAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/admin/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visual-posts': {
      id: '/admin/visual-posts'
      path: '/admin/visual-posts'
      fullPath: '/admin/visual-posts'
      preLoaderRoute: typeof AdminVisualPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$slug': {
      id: '/agent/$slug'
      path: '/agent/$slug'
      fullPath: '/agent/$slug'
      preLoaderRoute: typeof AgentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents/$agentId': {
      id: '/admin/agents/$agentId'
      path: '/admin/agents/$agentId'
      fullPath: '/admin/agents/$agentId'
      preLoaderRoute: typeof AdminAgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/run-demo-agent': {
      id: '/api/cron/run-demo-agent'
      path: '/api/cron/run-demo-agent'
      fullPath: '/api/cron/run-demo-agent'
      preLoaderRoute: typeof ApiCronRunDemoAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-register': {
      id: '/api/public/agent-register'
      path: '/api/public/agent-register'
      fullPath: '/api/public/agent-register'
      preLoaderRoute: typeof ApiPublicAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-api/$': {
      id: '/api/public/agent-api/$'
      path: '/api/public/agent-api/$'
      fullPath: '/api/public/agent-api/$'
      preLoaderRoute: typeof ApiPublicAgentApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-avatar/$': {
      id: '/api/public/agent-avatar/$'
      path: '/api/public/agent-avatar/$'
      fullPath: '/api/public/agent-avatar/$'
      preLoaderRoute: typeof ApiPublicAgentAvatarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/arena/$': {
      id: '/api/public/arena/$'
      path: '/api/public/arena/$'
      fullPath: '/api/public/arena/$'
      preLoaderRoute: typeof ApiPublicArenaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/conversations/$': {
      id: '/api/public/conversations/$'
      path: '/api/public/conversations/$'
      fullPath: '/api/public/conversations/$'
      preLoaderRoute: typeof ApiPublicConversationsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rewards-tick': {
      id: '/api/public/hooks/rewards-tick'
      path: '/api/public/hooks/rewards-tick'
      fullPath: '/api/public/hooks/rewards-tick'
      preLoaderRoute: typeof ApiPublicHooksRewardsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-demo-agent': {
      id: '/api/public/hooks/run-demo-agent'
      path: '/api/public/hooks/run-demo-agent'
      fullPath: '/api/public/hooks/run-demo-agent'
      preLoaderRoute: typeof ApiPublicHooksRunDemoAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-demo-campaign': {
      id: '/api/public/hooks/run-demo-campaign'
      path: '/api/public/hooks/run-demo-campaign'
      fullPath: '/api/public/hooks/run-demo-campaign'
      preLoaderRoute: typeof ApiPublicHooksRunDemoCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/post-visual/$': {
      id: '/api/public/post-visual/$'
      path: '/api/public/post-visual/$'
      fullPath: '/api/public/post-visual/$'
      preLoaderRoute: typeof ApiPublicPostVisualSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rewards/$': {
      id: '/api/public/rewards/$'
      path: '/api/public/rewards/$'
      fullPath: '/api/public/rewards/$'
      preLoaderRoute: typeof ApiPublicRewardsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  HowItWorksRoute: HowItWorksRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  RewardsRoute: RewardsRoute,
  SeasonRoute: SeasonRoute,
  SendYourAgentRoute: SendYourAgentRoute,
  SkillDotmdRoute: SkillDotmdRoute,
  AdminArenaRoute: AdminArenaRoute,
  AdminConversationsRoute: AdminConversationsRoute,
  AdminDemoAgentsRoute: AdminDemoAgentsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminVisualPostsRoute: AdminVisualPostsRoute,
  AgentSlugRoute: AgentSlugRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAgentsAgentIdRoute: AdminAgentsAgentIdRoute,
  ApiCronRunDemoAgentRoute: ApiCronRunDemoAgentRoute,
  ApiPublicAgentRegisterRoute: ApiPublicAgentRegisterRoute,
  ApiPublicAgentApiSplatRoute: ApiPublicAgentApiSplatRoute,
  ApiPublicAgentAvatarSplatRoute: ApiPublicAgentAvatarSplatRoute,
  ApiPublicArenaSplatRoute: ApiPublicArenaSplatRoute,
  ApiPublicConversationsSplatRoute: ApiPublicConversationsSplatRoute,
  ApiPublicHooksRewardsTickRoute: ApiPublicHooksRewardsTickRoute,
  ApiPublicHooksRunDemoAgentRoute: ApiPublicHooksRunDemoAgentRoute,
  ApiPublicHooksRunDemoCampaignRoute: ApiPublicHooksRunDemoCampaignRoute,
  ApiPublicPostVisualSplatRoute: ApiPublicPostVisualSplatRoute,
  ApiPublicRewardsSplatRoute: ApiPublicRewardsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
